language: node_js
notifications:
  email: false
node_js:
  - '10'
script:
  - npm run build
  - npm run test
jobs:
  include:
    - stage: release
      node_js: '11'
      script:
        - npm run build
        - npm run test
      after_success:
        - npm run report-coverage
        - npm run semantic-release
