import asText from "./astext";
import Tree from "./tree";
import serialize from "./serialize";
import { NODE_TYPES as Elements } from "./types";
declare const asTree: typeof Tree.fromRichText;
export { asText, asTree, serialize, Elements };
declare const _default: {
    asText: typeof asText;
    asTree: typeof Tree.fromRichText;
    serialize: typeof serialize;
    Elements: {
        heading1: string;
        heading2: string;
        heading3: string;
        heading4: string;
        heading5: string;
        heading6: string;
        paragraph: string;
        preformatted: string;
        strong: string;
        em: string;
        listItem: string;
        oListItem: string;
        list: string;
        oList: string;
        image: string;
        embed: string;
        hyperlink: string;
        label: string;
        span: string;
    };
};
export default _default;
