blank_issues_enabled: false
contact_links:
  - name: 👪 Prismic Community Forum
    url: https://community.prismic.io
    about: Ask questions about this package or raise issues directly related to Prismic. You will usually get support much quicker there!
